/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

//importing all the required components used from the library
import static java.awt.Color.BLACK;
import static java.awt.Color.DARK_GRAY;
import static java.awt.Color.GRAY;
import java.io.File;        //file class is Java's representation of a file or directory pathname
import java.io.FileReader;      
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;     //stores data of the table
import java.io.BufferedReader;      //used to read data line by line by readLine() method, inherits Reader class, makes performance fast
import java.io.FileNotFoundException;       //This exception is thrown during a failed attempt to open the file denoted by a specified pathname.
import java.io.FileWriter;
import javax.swing.table.TableRowSorter;
import java.io.IOException;
import java.util.LinkedList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.RowFilter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @SulavAdhikari/RajivKumarNayak-GroupCourseWork
 */
public class Main_CW extends javax.swing.JFrame {
    /**
     * Creates new form Main_CW
     */
    
    public Main_CW() {
        initComponents(); 
        jTextFieldTotal.setEditable(false);     //since total amount is created automatically no need to put manually.    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jPanelRental = new javax.swing.JPanel();
        jLabelRentalSubTitle = new javax.swing.JLabel();
        jLabelRequirement = new javax.swing.JLabel();
        jRadioButtonHome = new javax.swing.JRadioButton();
        jRadioButtonFlat = new javax.swing.JRadioButton();
        jLabelLocation = new javax.swing.JLabel();
        jComboBoxRoomNo = new javax.swing.JComboBox<>();
        jLabelRoomNo = new javax.swing.JLabel();
        jComboBoxLocation = new javax.swing.JComboBox<>();
        jLabelCost = new javax.swing.JLabel();
        jTextFieldCost = new javax.swing.JTextField();
        jTextFieldDeposit = new javax.swing.JTextField();
        jLabelDeposit = new javax.swing.JLabel();
        jPanelCustomer = new javax.swing.JPanel();
        jLabelCustomerSubTitle = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelAddress = new javax.swing.JLabel();
        jLabelPhone = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldAddress = new javax.swing.JTextField();
        jTextFieldPhone = new javax.swing.JTextField();
        jComboBoxID = new javax.swing.JComboBox<>();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jbtnRent = new javax.swing.JButton();
        jPanelAppliance = new javax.swing.JPanel();
        jLabelApplianceSubTitle = new javax.swing.JLabel();
        jLabelElectricityBill = new javax.swing.JLabel();
        jTextFieldElectricityBill = new javax.swing.JTextField();
        jLabelWaterBill = new javax.swing.JLabel();
        jTextFieldWaterBill = new javax.swing.JTextField();
        jLabelTax = new javax.swing.JLabel();
        jTextFieldTax = new javax.swing.JTextField();
        jLabelTotal = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JTextField();
        jLabelWIFI = new javax.swing.JLabel();
        jTextFieldWIFI = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jbtnReset = new javax.swing.JButton();
        jbtnClose = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jbtnSearch = new javax.swing.JButton();
        jTextFieldSearch = new javax.swing.JTextField();
        jComboBoxSearchByCombo = new javax.swing.JComboBox<>();
        jLabelSearch = new javax.swing.JLabel();
        jbtnImport = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 51));
        setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitle.setBackground(new java.awt.Color(153, 153, 153));
        jLabelTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("House/Flat Rental Management System");
        jLabelTitle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, -1));

        jPanelRental.setBackground(new java.awt.Color(153, 153, 153));
        jPanelRental.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelRentalSubTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelRentalSubTitle.setText("Rental Details");
        jLabelRentalSubTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabelRequirement.setText("Requirement:");

        jRadioButtonHome.setText("Home");
        jRadioButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonHomeActionPerformed(evt);
            }
        });

        jRadioButtonFlat.setText("Flat");
        jRadioButtonFlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFlatActionPerformed(evt);
            }
        });

        jLabelLocation.setText("Location:");

        jComboBoxRoomNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Number of Room", "1", "2", "3", "4", "5", "6", "7", "8" }));

        jLabelRoomNo.setText("Number Of Room:");

        jComboBoxLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Location", "Lalitpur", "Kirtipur", "Bhaktapur" }));

        jLabelCost.setText("Cost (in Rs):");

        jTextFieldCost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCostKeyTyped(evt);
            }
        });

        jTextFieldDeposit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDepositKeyTyped(evt);
            }
        });

        jLabelDeposit.setText("Deposit Amount (in Rs):");

        javax.swing.GroupLayout jPanelRentalLayout = new javax.swing.GroupLayout(jPanelRental);
        jPanelRental.setLayout(jPanelRentalLayout);
        jPanelRentalLayout.setHorizontalGroup(
            jPanelRentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelRentalSubTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRentalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRentalLayout.createSequentialGroup()
                        .addGroup(jPanelRentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelRoomNo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(jLabelLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelRequirement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabelCost, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabelDeposit, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxLocation, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRentalLayout.createSequentialGroup()
                        .addComponent(jRadioButtonHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonFlat, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBoxRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCost)
                    .addComponent(jTextFieldDeposit))
                .addGap(28, 28, 28))
        );
        jPanelRentalLayout.setVerticalGroup(
            jPanelRentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRentalLayout.createSequentialGroup()
                .addComponent(jLabelRentalSubTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelRentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRequirement, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonHome)
                    .addComponent(jRadioButtonFlat))
                .addGap(10, 10, 10)
                .addGroup(jPanelRentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelRentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelRentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCost, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCost, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelRental, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 380, 250));

        jPanelCustomer.setBackground(new java.awt.Color(153, 153, 153));
        jPanelCustomer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelCustomerSubTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCustomerSubTitle.setText("Customers Details");
        jLabelCustomerSubTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabelID.setText("Customer's ID Format:");

        jLabelName.setText("Customer's Name:");

        jLabelAddress.setText("Address: ");

        jLabelPhone.setText("Customer's Phone Number:");

        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });
        jTextFieldName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNameKeyTyped(evt);
            }
        });

        jTextFieldPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPhoneActionPerformed(evt);
            }
        });
        jTextFieldPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPhoneKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPhoneKeyTyped(evt);
            }
        });

        jComboBoxID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose ID Format", "Identity Card", "Citizenship Card", "Driving License" }));

        jLabelEmail.setText("Email Address:");

        jTextFieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldEmailKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEmailKeyTyped(evt);
            }
        });

        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanelCustomerLayout = new javax.swing.GroupLayout(jPanelCustomer);
        jPanelCustomer.setLayout(jPanelCustomerLayout);
        jPanelCustomerLayout.setHorizontalGroup(
            jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCustomerSubTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanelCustomerLayout.createSequentialGroup()
                        .addComponent(jLabelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(49, 49, 49))
                    .addComponent(jLabelAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPhone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldName)
                    .addComponent(jTextFieldAddress, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPhone, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxID, 0, 163, Short.MAX_VALUE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelCustomerLayout.setVerticalGroup(
            jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustomerLayout.createSequentialGroup()
                .addComponent(jLabelCustomerSubTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 370, 250));

        jbtnRent.setBackground(new java.awt.Color(153, 153, 153));
        jbtnRent.setText("Rent");
        jbtnRent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnRentMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnRentMouseExited(evt);
            }
        });
        jbtnRent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRentActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnRent, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 290, 90, 30));

        jPanelAppliance.setBackground(new java.awt.Color(153, 153, 153));
        jPanelAppliance.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelApplianceSubTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelApplianceSubTitle.setText("Appliances Details");
        jLabelApplianceSubTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabelElectricityBill.setText("Electricity Bill (in Rs):");

        jTextFieldElectricityBill.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldElectricityBillKeyTyped(evt);
            }
        });

        jLabelWaterBill.setText("Water Bill (in Rs):");

        jTextFieldWaterBill.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldWaterBillKeyTyped(evt);
            }
        });

        jLabelTax.setText("Tax Amount (in Rs):");

        jTextFieldTax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTaxKeyTyped(evt);
            }
        });

        jLabelTotal.setText("Total Payable Amount (in Rs):");

        jTextFieldTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTotalKeyTyped(evt);
            }
        });

        jLabelWIFI.setText("WIFI Bill (in Rs):");

        jTextFieldWIFI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldWIFIKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanelApplianceLayout = new javax.swing.GroupLayout(jPanelAppliance);
        jPanelAppliance.setLayout(jPanelApplianceLayout);
        jPanelApplianceLayout.setHorizontalGroup(
            jPanelApplianceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelApplianceSubTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelApplianceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelApplianceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelWaterBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelElectricityBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelWIFI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanelApplianceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldWaterBill, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldElectricityBill, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldWIFI, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTax, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanelApplianceLayout.setVerticalGroup(
            jPanelApplianceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelApplianceLayout.createSequentialGroup()
                .addComponent(jLabelApplianceSubTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanelApplianceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelElectricityBill, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldElectricityBill, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelApplianceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelWaterBill, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldWaterBill, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelApplianceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelApplianceLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelWIFI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(51, 51, 51))
                    .addGroup(jPanelApplianceLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jTextFieldWIFI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelApplianceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTax, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTax, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanelApplianceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        getContentPane().add(jPanelAppliance, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 30, 360, 250));

        jTable.setBackground(new java.awt.Color(153, 153, 153));
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Name", "Address", "Phone Number", "Deposit Amount", "Rent Location", "Total Room", "Cost", "Electricity Bill", "Water Bill", "WIFI Bill", "Tax Amount", "Total Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 1250, 150));

        jbtnReset.setBackground(new java.awt.Color(153, 153, 153));
        jbtnReset.setText("Reset");
        jbtnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnResetMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnResetMouseExited(evt);
            }
        });
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 290, 80, 30));

        jbtnClose.setBackground(new java.awt.Color(153, 153, 153));
        jbtnClose.setText("Close");
        jbtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 290, 80, 30));

        jbtnDelete.setBackground(new java.awt.Color(153, 153, 153));
        jbtnDelete.setText("Delete");
        jbtnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnDeleteMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnDeleteMouseExited(evt);
            }
        });
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 290, 80, 30));

        jbtnSearch.setText("Search By Room Number");
        jbtnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnSearchMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnSearchMouseExited(evt);
            }
        });
        jbtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 490, 160, 30));

        jTextFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSearchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSearchKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, 150, 30));

        jComboBoxSearchByCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Number of Room", "1", "2", "3", "4", "5", "6", "7", "8" }));
        jComboBoxSearchByCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSearchByComboActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxSearchByCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 490, 170, 30));

        jLabelSearch.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSearch.setText("Search By Name");
        getContentPane().add(jLabelSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 490, 90, 30));

        jbtnImport.setBackground(new java.awt.Color(153, 153, 153));
        jbtnImport.setForeground(new java.awt.Color(255, 255, 255));
        jbtnImport.setText("Import Data");
        jbtnImport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnImportMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnImportMouseExited(evt);
            }
        });
        jbtnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnImportActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnImport, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 120, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\Year 2\\Year 2 Module\\Emerging Programming Platforms\\CW\\18030008 Sulav Adhikari\\Login\\src\\Login\\pic2.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 530));

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 153));

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Open File");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator2);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("User help manual");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCloseActionPerformed
       
       //existing the window
       JOptionPane.showMessageDialog(this, "ALERT!! Do you want to exit.");
       System.exit(0);
    }//GEN-LAST:event_jbtnCloseActionPerformed

    private void jbtnRentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRentActionPerformed
        add();
    }//GEN-LAST:event_jbtnRentActionPerformed
    
    public void add() {
         //adding the details in the table
        JOptionPane.showMessageDialog(this, "Do you want to add above details in your below table.");
        if(jComboBoxID.getSelectedItem().toString().equals("Choose ID Format")||jTextFieldName.getText().equals("")||jTextFieldAddress.getText().equals("")||jTextFieldPhone.getText().equals("")||jTextFieldEmail.getText().equals("")||jTextFieldDeposit.getText().equals("")||jComboBoxLocation.getSelectedItem().toString().equals("Choose Location")||jComboBoxRoomNo.getSelectedItem().toString().equals("Select Number of Room")||jTextFieldCost.getText().equals("")||jTextFieldElectricityBill.getText().equals("")||jTextFieldWaterBill.getText().equals("")||jTextFieldWIFI.getText().equals("")||jTextFieldTax.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "You are requested to fill all the textfield");
        }else {            
            int strTotal = Integer.parseInt(jTextFieldDeposit.getText())+Integer.parseInt(jTextFieldCost.getText())+Integer.parseInt(jTextFieldElectricityBill.getText())+Integer.parseInt(jTextFieldWaterBill.getText())+Integer.parseInt(jTextFieldWIFI.getText())+Integer.parseInt(jTextFieldTax.getText());
            jTextFieldTotal.setText(Integer.toString(strTotal));
            
            String name = jTextFieldName.getText();
            String address = jTextFieldAddress.getText();
            String phone = jTextFieldPhone.getText();
            String deposit = jTextFieldDeposit.getText();           
            String location = jComboBoxLocation.getSelectedItem().toString();
            String roomNo = jComboBoxRoomNo.getSelectedItem().toString();
            String cost = jTextFieldCost.getText();          
            String electricity_bill = jTextFieldElectricityBill.getText();
            String water_bill = jTextFieldWaterBill.getText();
            String wifi = jTextFieldWIFI.getText();
            String tax = jTextFieldTax.getText();
            String total = jTextFieldTotal.getText();
            
            int rowCount = jTable.getRowCount();
            String check = "";
            for(int i = 0; i<rowCount; i++) {
                check = (String) jTable.getValueAt(i, 0).toString();
                if(check.equals(name)) {/* to check whether name is already entered or not*/
                    break;
                }
            }
            System.out.print(check+name);           
            if(check.equals(name)) {
                JOptionPane.showMessageDialog(rootPane,"Your Data Is Already Entered");
            }else {
                if(Integer.parseInt(deposit)>0||Integer.parseInt(cost)>0||Integer.parseInt(electricity_bill)>0||Integer.parseInt(water_bill)>0||Integer.parseInt(wifi)>0||Integer.parseInt(tax)>0) {
                    String filepath = "C:\\Users\\User\\Documents\\Year 2\\Year 2 Module\\Emerging Programming Platforms\\CW\\18030008 Sulav Adhikari\\Login\\src\\Login\\coursework.csv";
                    File newfile = new File(filepath);
                try {
                write("\n"+name+","+address+","+phone+","+deposit+","+location+","+roomNo+","+cost+","+electricity_bill+","+water_bill+","+wifi+","+tax+","+total,newfile);
                }catch(IOException ex) {
                    Logger.getLogger(Main_CW.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    importData();
                }catch(IOException ex) {
                    Logger.getLogger(Main_CW.class.getName()).log(Level.SEVERE, null, ex);
                }
                }else {
                    JOptionPane.showMessageDialog(rootPane,"Invalid");  
                }
            }                                         
        }                         
            jComboBoxID.setSelectedItem("Choose ID Format");
            jTextFieldName.setText("");
            jTextFieldAddress.setText("");
            jTextFieldPhone.setText("");
            jTextFieldEmail.setText("");
            jTextFieldDeposit.setText("");
            jRadioButtonHome.setSelected(false);
            jRadioButtonFlat.setSelected(false);
            jComboBoxLocation.setSelectedItem("Choose Location");
            jComboBoxRoomNo.setSelectedItem("Select Number of Room");
            jTextFieldCost.setText("");         
            jTextFieldElectricityBill.setText("");
            jTextFieldWaterBill.setText("");
            jTextFieldWIFI.setText("");
            jTextFieldTax.setText("");
            jTextFieldTotal.setText(""); 
    }
    
    public void write(String a,File file) throws IOException {
        
        FileWriter fw = new FileWriter(file,true);
        fw.write(a);
        fw.close();
    }
    
    public int binarySearch(int low,int high,int search,LinkedList number) {
        
        if(low <= high) {
            int mid = (low+high)/2;
            if(Integer.parseInt(number.get(mid).toString()) == search) {
                return Integer.parseInt(number.get(mid).toString());
            }else if(Integer.parseInt(number.get(mid).toString()) < search) {
                return binarySearch(mid+1,high,search,number);               
            }else if(Integer.parseInt(number.get(mid).toString()) > search) {
                return binarySearch(low,mid-1,search,number) ;
            }
       }
        return -1;
   }
   
    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        reset();      
    }//GEN-LAST:event_jbtnResetActionPerformed

    public void reset() {
         //reseting the value for making it to enter again.
        if(!(jComboBoxID.getSelectedItem().toString().equals("")&&jTextFieldName.getText().equals("")&&jTextFieldAddress.getText().equals("")&&jTextFieldPhone.getText().equals("")&&jTextFieldEmail.getText().equals("")&&jTextFieldDeposit.getText().equals("")&&jComboBoxLocation.getSelectedItem().toString().equals("")&&jComboBoxRoomNo.getSelectedItem().toString().equals("")&&jTextFieldElectricityBill.getText().equals("")&&jTextFieldWaterBill.getText().equals("")&&jTextFieldTax.getText().equals("")&&jTextFieldTotal.getText().equals(""))) {           
            jComboBoxID.setSelectedItem("Choose ID Format");
            jTextFieldName.setText("");
            jTextFieldAddress.setText("");
            jTextFieldPhone.setText("");
            jTextFieldEmail.setText("");
            jTextFieldDeposit.setText("");
            jRadioButtonHome.setSelected(false);
            jRadioButtonFlat.setSelected(false);
            jComboBoxLocation.setSelectedItem("Choose Location");
            jComboBoxRoomNo.setSelectedItem("Select Number of Room");
            jTextFieldCost.setText("");         
            jTextFieldElectricityBill.setText("");
            jTextFieldWaterBill.setText("");
            jTextFieldWIFI.setText("");
            jTextFieldTax.setText("");
            jTextFieldTotal.setText("");
        }
    }
    private void jTextFieldPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPhoneKeyTyped
        
        //disables the alphabets pressed. Only accepts the number value.
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c))) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldPhoneKeyTyped

    private void jTextFieldDepositKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDepositKeyTyped
        
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c))) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldDepositKeyTyped

    private void jTextFieldElectricityBillKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldElectricityBillKeyTyped
        
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c))) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldElectricityBillKeyTyped

    private void jTextFieldWaterBillKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldWaterBillKeyTyped
        
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c))) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldWaterBillKeyTyped

    private void jTextFieldTaxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTaxKeyTyped
        
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c))) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldTaxKeyTyped

    private void jTextFieldTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTotalKeyTyped
        
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c))) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldTotalKeyTyped

    private void jTextFieldNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNameKeyTyped
        
        //name cannot be any number so,
        char c=evt.getKeyChar();
        if((Character.isDigit(c))) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNameKeyTyped

    private void jTextFieldEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmailKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailKeyTyped

    private void jTextFieldPhoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPhoneKeyReleased
        
    }//GEN-LAST:event_jTextFieldPhoneKeyReleased

    private void jTextFieldPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneActionPerformed

    private void jTextFieldEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmailKeyReleased
         
        //Regex(Regular Expression):: Checking for email validation.
        String Email_Pattern = "^[a-zA-Z0-9]{1,20}@[a-zA-Z]{5,20}.[a-zA-Z]{2,5}$";
        Pattern pattern = Pattern.compile(Email_Pattern);
        Matcher regexmatch = pattern.matcher(jTextFieldEmail.getText());
        if(!regexmatch.matches()) {
            jLabel1.setText("  Invalid*");
        }else {
          jLabel1.setText("  Valid");
        }
    }//GEN-LAST:event_jTextFieldEmailKeyReleased

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked

    }//GEN-LAST:event_jTableMouseClicked

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
                                  
        int SelectedRowIndex = jTable.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)jTable.getModel();
        model.removeRow(SelectedRowIndex);
        JOptionPane.showMessageDialog(this, "Information Deleted.");          
    }//GEN-LAST:event_jbtnDeleteActionPerformed
    
    public void importData() throws FileNotFoundException, IOException {
        
        //importing the saved data to the table
        String filepath = "C:\\Users\\User\\Documents\\Year 2\\Year 2 Module\\Emerging Programming Platforms\\CW\\18030008 Sulav Adhikari\\Login\\src\\Login\\coursework.csv";
        File file = new File(filepath);
        jTable.setModel(new DefaultTableModel(null,new String[] {"","","","","","","","","","","",""}));
        BufferedReader br = new BufferedReader(new FileReader(file));
        String firstline = br.readLine().trim();
        String[] columnsName = firstline.split(",");
        DefaultTableModel model = (DefaultTableModel)jTable.getModel();
        model.setColumnIdentifiers(columnsName);    
        Object[] tableLines = br.lines().toArray();
     
        for(int i = 0; i < tableLines.length; i++) {
            String line = tableLines[i].toString().trim();
            String[] dataRow = line.split(",");
            model.addRow(dataRow);
        } 
    }

    private void jbtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSearchActionPerformed
        searchByCombobox();
    }//GEN-LAST:event_jbtnSearchActionPerformed

    public void searchByCombobox() {
        
        //searching combobox data using Binary Search Algorithm based on the number of room.
        try {
        LinkedList <Integer> RoomNo =new LinkedList<>();
        //LinkedList <String> Name = new LinkedList<>();
        int a = jTable.getRowCount();
        for(int i=0;i<a;i++) {
            int roomno = Integer.parseInt(jTable.getValueAt(i,5).toString());
            //String name = (String)jTable.getValueAt(i,0);
            if (roomno != 0) {
                RoomNo.add(roomno);
               // Name.add(name);
            }
       }       
        int n = RoomNo.size(); 
        for (int i = 0; i < n-1; i++) {
            int min_index = i; 
            for (int j = i+1; j < n; j++) { 
                if(RoomNo.get(j) < RoomNo.get(min_index)) {
                    min_index = j; 
                }
                int temp = RoomNo.get(min_index); 
               //String temp1=Name.get(min_index);
                RoomNo.set(min_index, RoomNo.get(i)); 
                RoomNo.set(i, temp); 
                //Name.set(min_index, Name.get(i)); 
                //Name.set(i, temp1);
            }
       }
        int search = Integer.parseInt(jComboBoxSearchByCombo.getSelectedItem().toString());
        int low =0;
        int high = RoomNo.size()-1;
        int find = binarySearch(low,high,search,RoomNo);    //binary search implementation
        if (find == -1) {
            JOptionPane.showMessageDialog(rootPane, "Searched data cannot be found");
            }else {
                String tosearch=jComboBoxSearchByCombo.getSelectedItem().toString();
                for (int i=0; i<jTable.getRowCount();i++) {
                    String findval=jTable.getValueAt(i,5).toString();
                    if(findval.equals(tosearch)) {
                        JOptionPane.showMessageDialog(rootPane,"Customer Name:= "+jTable.getValueAt(i,0).toString()+"\n Address:=              "+jTable.getValueAt(i,1).toString()+"\n Rented Location:= "+ jTable.getValueAt(i,4).toString()+"\n Rent Cost:=           "+ jTable.getValueAt(i,6).toString()+"\n Total Amount:=      "+ jTable.getValueAt(i,11).toString());                     
                    break;
                    }
                }    
            }   
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error");
        }
    }
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        //importing file to the table through menubar
        try {
            importData();
        }catch(IOException ex) {
            Logger.getLogger(Main_CW.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "File Imported!!");
        jMenuItem1.setEnabled(false);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        //closing the window from the menu.
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        
        //seeking the help through the help of menubar.
        try {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+"C:\\Users\\User\\Documents\\Year 2\\Year 2 Module\\Emerging Programming Platforms\\CW\\18030008 Sulav Adhikari\\Login\\src\\Login\\Help User Manual.pdf");
        }catch(Exception e) {
        JOptionPane.showMessageDialog(this, "Error Input Given!!");
        }
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jTextFieldWIFIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldWIFIKeyTyped
        
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c))) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldWIFIKeyTyped

    private void jTextFieldCostKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCostKeyTyped
        
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c))) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCostKeyTyped

    private void jRadioButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonHomeActionPerformed
        
        //only one radio button can be selected at a time.
        if (jRadioButtonHome.isSelected()) {
            jRadioButtonFlat.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonHomeActionPerformed

    private void jRadioButtonFlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFlatActionPerformed
        
        if (jRadioButtonFlat.isSelected()) {
            jRadioButtonHome.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonFlatActionPerformed

    public void searchByName() {
        //search the data of the table by any means(name).
        DefaultTableModel model = (DefaultTableModel)jTable.getModel();
        String search = jTextFieldSearch.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        jTable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }
    private void jTextFieldSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchKeyReleased
       searchByName();
    }//GEN-LAST:event_jTextFieldSearchKeyReleased

    private void jbtnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnImportActionPerformed
       
        try {
            importData();
        }catch(IOException ex) {
            Logger.getLogger(Main_CW.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnImportActionPerformed

    private void jComboBoxSearchByComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSearchByComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSearchByComboActionPerformed

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jTextFieldSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchKeyTyped
        char c=evt.getKeyChar();
        if((Character.isDigit(c))) {
            evt.consume();
        } 
    }//GEN-LAST:event_jTextFieldSearchKeyTyped

    private void jbtnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnDeleteMouseClicked
        jbtnDelete.setBackground(DARK_GRAY);
    }//GEN-LAST:event_jbtnDeleteMouseClicked

    private void jbtnDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnDeleteMouseExited
        jbtnDelete.setBackground(GRAY);
    }//GEN-LAST:event_jbtnDeleteMouseExited

    private void jbtnImportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnImportMouseClicked
        jbtnImport.setBackground(BLACK);
    }//GEN-LAST:event_jbtnImportMouseClicked

    private void jbtnImportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnImportMouseExited
        jbtnImport.setBackground(DARK_GRAY);
    }//GEN-LAST:event_jbtnImportMouseExited

    private void jbtnRentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnRentMouseClicked
        jbtnRent.setBackground(DARK_GRAY);
    }//GEN-LAST:event_jbtnRentMouseClicked

    private void jbtnRentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnRentMouseExited
        jbtnRent.setBackground(GRAY);
    }//GEN-LAST:event_jbtnRentMouseExited

    private void jbtnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnResetMouseClicked
        jbtnReset.setBackground(DARK_GRAY);
    }//GEN-LAST:event_jbtnResetMouseClicked

    private void jbtnResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnResetMouseExited
        jbtnReset.setBackground(GRAY);
    }//GEN-LAST:event_jbtnResetMouseExited

    private void jbtnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnSearchMouseClicked
        jbtnSearch.setBackground(DARK_GRAY);
    }//GEN-LAST:event_jbtnSearchMouseClicked

    private void jbtnSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnSearchMouseExited
        jbtnSearch.setBackground(GRAY);
    }//GEN-LAST:event_jbtnSearchMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_CW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_CW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_CW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_CW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_CW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxID;
    private javax.swing.JComboBox<String> jComboBoxLocation;
    private javax.swing.JComboBox<String> jComboBoxRoomNo;
    private javax.swing.JComboBox<String> jComboBoxSearchByCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelApplianceSubTitle;
    private javax.swing.JLabel jLabelCost;
    private javax.swing.JLabel jLabelCustomerSubTitle;
    private javax.swing.JLabel jLabelDeposit;
    private javax.swing.JLabel jLabelElectricityBill;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelLocation;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPhone;
    private javax.swing.JLabel jLabelRentalSubTitle;
    private javax.swing.JLabel jLabelRequirement;
    private javax.swing.JLabel jLabelRoomNo;
    private javax.swing.JLabel jLabelSearch;
    private javax.swing.JLabel jLabelTax;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelWIFI;
    private javax.swing.JLabel jLabelWaterBill;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanelAppliance;
    private javax.swing.JPanel jPanelCustomer;
    private javax.swing.JPanel jPanelRental;
    private javax.swing.JRadioButton jRadioButtonFlat;
    private javax.swing.JRadioButton jRadioButtonHome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldCost;
    private javax.swing.JTextField jTextFieldDeposit;
    private javax.swing.JTextField jTextFieldElectricityBill;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPhone;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JTextField jTextFieldTax;
    private javax.swing.JTextField jTextFieldTotal;
    private javax.swing.JTextField jTextFieldWIFI;
    private javax.swing.JTextField jTextFieldWaterBill;
    private javax.swing.JButton jbtnClose;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnImport;
    private javax.swing.JButton jbtnRent;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnSearch;
    // End of variables declaration//GEN-END:variables
}